# Generated by Django 4.1.3 on 2022-11-23 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('today', 'امروز'), ('necessary', 'ضروروی'), ('zremind', 'یادآوری')], max_length=16)),
                ('remind_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('family', models.CharField(max_length=126)),
                ('field', models.CharField(max_length=256)),
                ('university', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=125)),
                ('doctor_adviser', models.CharField(max_length=125)),
                ('money', models.IntegerField()),
                ('debt_payment1', models.FileField(upload_to='')),
                ('debt_payment2', models.FileField(upload_to='')),
                ('debt_payment3', models.FileField(upload_to='')),
                ('start_date', models.DateTimeField()),
                ('proposal', models.FileField(upload_to='')),
                ('ch123', models.FileField(upload_to='')),
                ('ch45', models.FileField(upload_to='')),
                ('translation', models.CharField(max_length=64)),
                ('RAC', models.CharField(max_length=64)),
                ('representative', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'family')},
            },
        ),
    ]
