# Generated by Django 4.1.3 on 2022-11-24 08:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='ch123',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='ch45',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='debt_payment1',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='debt_payment2',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='debt_payment3',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='proposal',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
    ]
