# Generated by Django 4.1.3 on 2022-11-26 21:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_ch123_alter_main_ch45_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='RAC',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='main',
            name='ch123',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='ch45',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='debt_payment1',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='debt_payment2',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='debt_payment3',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='field',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='main',
            name='proposal',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='main',
            name='representative',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='main',
            name='translation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='main',
            name='university',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
