# Generated by Django 4.1.3 on 2022-12-26 23:47

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_main_doctor_adviser_alter_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='translation',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
    ]
